APP-921 support comments and run change tracking
Preciselyco/unioffice pull request #1
Opened 2020-11-16 09:03 UTC by preciselytom

Add docx-tool command.

Add missing contents to CT_RunTrackChange.

Add high-level type RunTrackChange for creating a CT_RunTrackChange.

Fix broken reading and writing of timestamps; docx uses RFC3339, not the Go default format.

Add high-level types Markup and MarkupRange for creating comment markups.

Add support for the comments.xml file.

Add support for the commentsExtended.xml file and the types CT_CommentsEx and CT_CommentEx.

Add high-level types Comments and Comment for creating comments.

Add high-level types CommentsExtended and CommentExtended for creating comment relationship information.

Refactor the definition of content types and file relationships when writing a docx.
This was buggy before; if a certain file was missing when reading a docx, it would be missing when writing as well.

Update unit tests and expected files.
Add unit tests for added functionality.

2020-11-16 13:03 UTC, antonlindstrom requested changes

2020-11-16 13:18 UTC, preciselytord approved these changes
lgtm

2020-11-16 13:19 UTC, preciselytom commented on cmd/docx-tool/main.go
> +// Added by Precisely.
Okay. Should I remove the "Begin code added by Precisely" comments as well?

2020-11-16 13:22 UTC, antonlindstrom commented on cmd/docx-tool/main.go
> +// Added by Precisely.
Yes, I don't think that's needed.

2020-11-16 17:56 UTC, preciselytom commented
@antonlindstrom Please see the last commit for your requested changes.

2020-11-17 09:37 UTC, antonlindstrom approved these changes

2020-11-17 09:54 UTC, merged